# ===== ??????? ???? ?????? =====
spring.datasource.url=jdbc:postgresql://109.198.190.115:32322/ManakovaA
spring.datasource.username=student
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=your-super-secret-key-for-jwt-must-be-at-least-256-bits-long-please-change-it
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG